name: ladybird
description: "An unofficial embedding library for Ladybird"
version: 0.0.1
homepage: 0.0.1

native_assets: true

environment:
  sdk: ^3.11.0
  flutter: '>=3.3.0'


dependencies:
  code_assets: ^1.0.0
  data_assets: ^0.19.6
  ffi: ^2.2.0
  flutter:
    sdk: flutter
  hooks: ^1.0.1
  native_toolchain_c: ^0.17.4
  plugin_platform_interface: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  ffigen: ^12.0.0

flutter:
  config:
    # Ideally we have this but I'm not sure how possible it is to package
    enable-swift-package-manager: false
  plugin:
    platforms:
      linux:
        pluginClass: LibbirdPlugin
      macos:
        pluginClass: LibbirdPlugin
  
ffigen:
  name: LibbirdBindings
  description: Bindings to libbird C++ engine
  output: 'lib/src/generated/engine_bindings.g.dart'
  headers:
    entry-points:
      - 'cpp/engine.h'
  compiler-opts:
    - '-Icpp'
